version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app:rw
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
      - DOCKER_IMAGE_REPO=${DOCKER_IMAGE_REPO}
    command: npm run dev -- --host 0.0.0.0
