apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  namespace: bluegreen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
        - name: myapp
          image: IMAGE_PLACEHOLDER   # replaced by deploy-bluegreen.sh
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
