apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: bluegreen
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # access via http://desktop_ip:30080
