apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: ${K8S_NAMESPACE}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: ${NODE_PORT}
  selector:
    app: myapp
    version: blue
