name: CI/CD Blue-Green

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & Push image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
        # run: npm ci

      - name: Lint
        run: npm run lint

      # - name: Run tests
      #   run: npm run test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            docker.io/milanr853/blue-green-deployment:${{ github.sha }}
            docker.io/milanr853/blue-green-deployment:latest
          build-args: |
            VITE_APP_VERSION=${{ github.sha }}

      - name: Set image-tag output
        id: set-tag
        run: echo "image-tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to k3s (desktop)
    needs: build
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure deploy script executable
        run: chmod +x ./k8s/deploy-bluegreen.sh

      - name: Deploy using deploy-bluegreen.sh
        env:
          DOCKER_IMAGE_REPO: docker.io/milanr853/blue-green-deployment
        run: |
          ./k8s/deploy-bluegreen.sh "${{ needs.build.outputs.image-tag }}"
